import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { HandGestureProvider } from "./_context/HandGestureContext";
import HandCursor from "./_components/HandCursor";

import { Agentation } from "agentation";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="overflow-y-auto">
        <TRPCReactProvider>
          <HandGestureProvider>
            {children}
            <HandCursor />
            {process.env.NODE_ENV === "development" && <Agentation />}
          </HandGestureProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
